#pragma once
#ifndef INCLUDE_PHOENIX_CUID_H
#define INCLUDE_PHOENIX_CUID_H

enum CUID : unsigned int {
    CUID_WIN32WINDOW = 1,
    CUID_IGAMELOOP = 2,
    CUID_SDLWINDOW = 3,
    CUID_IRENDERER2D = 4,
    CUID_EVENTMANAGER = 5
};

#endif //INCLUDE_PHOENIX_CUID_H
